name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Raw SSH Debug
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -vvv ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "echo 'Hello from Raw SSH'; uname -a; exit"

      - name: Copy files to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "go.mod,go.sum,main.go,Dockerfile,docker-compose.yml,views,static"
          target: "~/city-r"
          rm: true
          timeout: 10m
          command_timeout: 10m
          debug: true
          tar_exec: true

      - name: Execute docker-compose via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          command_timeout: 30m
          script: |
            cd ~/city-r
            docker compose down || true
            docker compose up -d --build
            docker image prune -f
